import '../ai/ai_models.dart';
import '../ai/offline_ai_service.dart';
import '../flashcards/flashcard_generator.dart';
import '../flashcards/flashcard_models.dart';
import '../flashcards/flashcard_repository.dart';
import '../library/library_models.dart';
import '../library/library_repository.dart';
import '../pdf/pdf_models.dart';
import '../pdf/pdf_service.dart';
import '../quiz/local_quiz_repository.dart';
import '../scan/scan_models.dart';

class StudyPack {
  const StudyPack({
    required this.document,
    required this.pdfBytes,
    required this.deck,
  });

  final LibraryDocument document;
  final List<int> pdfBytes;
  final FlashcardDeck? deck;
}

class StudyPackBuilder {
  const StudyPackBuilder({
    required PdfService pdfService,
    required LibraryRepository libraryRepository,
    required FlashcardGenerator flashcardGenerator,
    required FlashcardRepository flashcardRepository,
  })  : _pdfService = pdfService,
        _libraryRepository = libraryRepository,
        _flashcardGenerator = flashcardGenerator,
        _flashcardRepository = flashcardRepository;

  final PdfService _pdfService;
  final LibraryRepository _libraryRepository;
  final FlashcardGenerator _flashcardGenerator;
  final FlashcardRepository _flashcardRepository;

  Future<StudyPack> buildFromScan({
    required ScanResult scanResult,
    required String title,
    required String subject,
    required DateTime now,
    bool generateCards = true,
    int cardCount = 15,
    bool generateQuizzes = true,
    int quizzesPerDifficulty = 5,
    String? summary,
    List<String> bullets = const [],
    List<SummarySectionResult> sections = const [],
    String? footer,
  }) async {
    final payload = PdfDocumentPayload(
      id: 'doc_${now.microsecondsSinceEpoch}',
      title: title,
      subtitle: subject,
      subject: subject,
      body: (summary != null && summary.trim().isNotEmpty)
          ? summary.trim()
          : scanResult.fullText,
      createdAt: now,
      sourceText: scanResult.fullText,
      bullets: bullets,
      footer: footer ?? 'Generated by PeckPapers',
    );

    final pdfBytes = await _pdfService.buildPdf(payload);

    FlashcardDeck? deck;
    if (generateCards) {
      final cards = await _flashcardGenerator.generate(
        sourceText: scanResult.fullText,
        subject: subject,
        count: cardCount,
      );
      deck = FlashcardDeck(
        id: 'deck_${now.microsecondsSinceEpoch}',
        title: title,
        cards: cards,
        createdAt: now,
        docId: payload.id,
      );
      await _flashcardRepository.saveDeck(deck);
    }

    // Generate quizzes
    var easyQuizCount = 0;
    var mediumQuizCount = 0;
    var difficultQuizCount = 0;

    if (generateQuizzes) {
      try {
        final allQuizzes = await OfflineAiService.instance
            .generateAllDifficultyQuizzes(
              scanResult.fullText,
              subject: subject,
              countPerDifficulty: quizzesPerDifficulty,
            );

        final quizRepo = LocalQuizRepository.instance;
        final docId = payload.id;

        easyQuizCount = allQuizzes[QuestionDifficulty.easy]?.length ?? 0;
        mediumQuizCount = allQuizzes[QuestionDifficulty.medium]?.length ?? 0;
        difficultQuizCount = allQuizzes[QuestionDifficulty.difficult]?.length ?? 0;

        // Save each difficulty level separately
        if (easyQuizCount > 0) {
          await quizRepo.saveQuiz(
            docId,
            QuestionDifficulty.easy,
            allQuizzes[QuestionDifficulty.easy]!,
          );
        }
        if (mediumQuizCount > 0) {
          await quizRepo.saveQuiz(
            docId,
            QuestionDifficulty.medium,
            allQuizzes[QuestionDifficulty.medium]!,
          );
        }
        if (difficultQuizCount > 0) {
          await quizRepo.saveQuiz(
            docId,
            QuestionDifficulty.difficult,
            allQuizzes[QuestionDifficulty.difficult]!,
          );
        }
      } catch (_) {
        // Quiz generation failed, but we continue
      }
    }

    final document = LibraryDocument(
      id: payload.id,
      title: title,
      subject: subject,
      pageCount: scanResult.pages.length,
      cardCount: deck?.cards.length ?? 0,
      createdAt: now,
      textContent: scanResult.fullText,
      summary: (summary != null && summary.isNotEmpty)
          ? LibrarySummary(
              text: summary,
              bullets: bullets,
              sections: sections
                  .map((s) => SummarySection(
                        topic: s.topic,
                        content: s.content,
                        bullets: s.bullets,
                      ))
                  .toList(),
              generatedAt: now,
            )
          : null,
      easyQuizCount: easyQuizCount,
      mediumQuizCount: mediumQuizCount,
      difficultQuizCount: difficultQuizCount,
    );
    await _libraryRepository.upsertDocument(document);

    return StudyPack(
      document: document,
      pdfBytes: pdfBytes,
      deck: deck,
    );
  }
}
